version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - movie-dev-db-data:/var/libs/postgresql/data
    environment:
      - POSTGRES_DB=movieDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test
  app:
    build:
      context: .
    command: sh -c "uvicorn main:app --reload"
    volumes:
      - ./movie:/movie
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  movie-dev-db-data: