version: '3.9'

services:
  app:
    build:
      context: .
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000 --env-file .env"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - note-dev-db-data:/var/libs/postgresql/data
    env_file:
      - ./app/.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "notes"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  note-dev-db-data: